---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	normalize_request(normalize_request)
	need_context(need_context)
	health_analysis(health_analysis)
	generate_response(generate_response)
	validate_response(validate_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> normalize_request;
	generate_response --> validate_response;
	health_analysis --> generate_response;
	normalize_request --> need_context;
	validate_response --> __end__;
	need_context -.-> normalize_request;
	need_context -.-> health_analysis;
	need_context -.-> generate_response;
	need_context -.-> validate_response;
	need_context -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
