---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_user_context(load_user_context)
	intent_classification(intent_classification)
	chat_graph(chat_graph)
	report_graph(report_graph)
	action_graph(action_graph)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_user_context;
	intent_classification -.-> action_graph;
	intent_classification -.-> chat_graph;
	intent_classification -.-> report_graph;
	load_user_context --> intent_classification;
	action_graph --> __end__;
	chat_graph --> __end__;
	report_graph --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
