---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	gather(gather)
	synthesize(synthesize)
	sleep(sleep)
	power(power)
	posture(posture)
	iot(iot)
	general(general)
	__end__([<p>__end__</p>]):::last
	__start__ --> gather;
	gather -.-> general;
	gather -.-> iot;
	gather -.-> posture;
	gather -.-> power;
	gather -.-> sleep;
	general --> synthesize;
	iot --> synthesize;
	posture --> synthesize;
	power --> synthesize;
	sleep --> synthesize;
	synthesize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
